services:
  backend:
    container_name: halal-check-backend
    build: ./backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend/.env:/app/.env
      - ./data:/app/data
    env_file:
      - ./backend/.env

  frontend:
    container_name: halal-check-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: https://api.afood.khasanjon.dev
    ports:
      - "3000:80"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env

volumes:
  data:

