services:
  backend:
    container_name: halal-check-backend
    build:
      context: ./backend
      dockerfile: ../devops/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    env_file:
      - ./backend/.env

  frontend:
    container_name: halal-check-frontend
    build:
      context: ./nginx
      dockerfile: ../devops/frontend/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env

volumes:
  data: